package com.devops.agent.service;

import com.devops.agent.model.AnalysisResult;
import com.devops.agent.model.ProjectContext;
import com.devops.agent.util.ProjectScanner;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

@Service
public class AnalysisService {

    private static final Logger log =
            LoggerFactory.getLogger(AnalysisService.class);

    private final GitService gitService;
    private final AiService aiService;
    private final FallbackGenerator fallbackGenerator;

    public AnalysisService(
            GitService gitService,
            AiService aiService,
            FallbackGenerator fallbackGenerator
    ) {
        this.gitService = gitService;
        this.aiService = aiService;
        this.fallbackGenerator = fallbackGenerator;
    }

    public AnalysisResult analyzeRepo(String repoUrl) {

        Path dir = null;

        try {
            log.info(">>> Starting repo analysis: {}", repoUrl);

            dir = gitService.cloneRepo(repoUrl);

            ProjectContext ctx = ProjectScanner.scan(dir);

            return runAnalysis(ctx);

        } catch (Exception e) {
            log.error(">>> Repo analysis failed: {}", e.getMessage());
            throw new RuntimeException("Repo analysis failed");
        } finally {
            gitService.cleanup(dir);
        }
    }

    public AnalysisResult analyzeUpload(MultipartFile file) {

        Path temp = null;

        try {
            log.info(">>> Starting upload analysis: {}", file.getOriginalFilename());

            temp = Files.createTempDirectory("upload");

            unzip(file.getInputStream(), temp);

            ProjectContext ctx = ProjectScanner.scan(temp);

            return runAnalysis(ctx);

        } catch (Exception e) {
            log.error(">>> Upload analysis failed: {}", e.getMessage());
            throw new RuntimeException("Upload analysis failed");
        } finally {
            gitService.cleanup(temp);
        }
    }

    private AnalysisResult runAnalysis(ProjectContext ctx) {

        log.info("========================================");
        log.info("  DEVOPS AGENT - ANALYSIS STARTED");
        log.info("  Project Type : {}", ctx.getProjectType());
        log.info("========================================");

        // ── STEP 1: Main Analysis (AI or Fallback) ───────────────────
        AnalysisResult result = aiService.analyze(ctx);

        if (result != null) {
            log.info("[AI]       Main analysis    --> GENERATED BY AI (Groq)");
        } else {
            log.warn("[FALLBACK] Main analysis    --> AI unavailable, using fallback generator");
            result = fallbackGenerator.generate(ctx);
        }

        // ── STEP 2: README (static template, not an AI call) ─────────
        result.setReadme(aiService.generateReadme(ctx));
        log.info("[STATIC]   README           --> generated from template");

        // ── STEP 3: Repo Explanation (AI tries, may fall back) ───────
        // AiService.explainRepo handles its own fallback internally and
        // already logs the outcome -- we just need to correctly reflect
        // here whether AI actually worked or not.
        String explanation = aiService.explainRepo(ctx);
        result.setRepoExplanation(explanation);

        // Detect whether AiService returned fallback content by checking
        // for the known fallback marker. AiService logs the real outcome;
        // we just need the AnalysisService banner to be accurate.
        boolean explainUsedFallback = explanation != null
                && explanation.startsWith("## Project Overview\nThis is a ");

        if (explainUsedFallback) {
            log.warn("[FALLBACK] Repo explanation --> AI unavailable, using fallback");
        } else {
            log.info("[AI]       Repo explanation --> GENERATED BY AI (Groq)");
        }

        // ── STEP 4: Security Scan ────────────────────────────────────
        SecurityScanner.scan(ctx, result);
        log.info("[SCANNER]  Security scan    --> COMPLETED");

        log.info("========================================");
        log.info("  DEVOPS AGENT - ANALYSIS COMPLETE");
        log.info("========================================");

        return result;
    }

    private void unzip(InputStream is, Path target) throws Exception {

        try (ZipInputStream zis = new ZipInputStream(is)) {

            ZipEntry entry;

            while ((entry = zis.getNextEntry()) != null) {

                Path newPath =
                        target.resolve(entry.getName()).normalize();

                if (!newPath.startsWith(target)) {
                    // zip slip protection
                    zis.closeEntry();
                    continue;
                }

                if (entry.isDirectory()) {
                    Files.createDirectories(newPath);
                } else {
                    Files.createDirectories(newPath.getParent());
                    Files.copy(zis, newPath);
                }

                zis.closeEntry();
            }
        }
    }
}